# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/196fdf21-6718-4828-a867-3989d8b81a0f";
      fsType = "btrfs";
      options = [ "subvol=rootfs" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/196fdf21-6718-4828-a867-3989d8b81a0f";
      fsType = "btrfs";
      options = [ "subvol=.snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8D33-1D15";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/196fdf21-6718-4828-a867-3989d8b81a0f";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/196fdf21-6718-4828-a867-3989d8b81a0f";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/196fdf21-6718-4828-a867-3989d8b81a0f";
      fsType = "btrfs";
      options = [ "subvol=var/log" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1f7648d4-4779-4856-8f6c-cc680eabfcec"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
